spring:
  datasource:
    url: ${MYSQL_CONNECT}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_ID}
            clientSecret: ${GOOGLE_SECRET_CODE}
            scope:
              - email
              - profile
server:
  port: ${PORT}
jwt:
  secret-key: ${JWT_SECRET_KEY}
  token-expire-time: ${JWT_TOKEN_EXPIRE_TIME}
  refresh-expire-time: ${JWT_REFRESH_TOKEN_EXPIRE_TIME}
